site:
  title: Cairo 1.0 docs
  start_page: ROOT::index.adoc

content:
  sources:
    - url: https://github.com/starkware-libs/cairo.git
#      branches: 'steve_fix_antora_build_errors'
      branches: 'HEAD'
      start_paths:
        - docs/reference/src/components/cairo
ui:
  bundle:
    url: https://github.com/starknet-io/starknet-docs-antora-ui/raw/HEAD/build/ui-bundle.zip
    snapshot: true
  supplemental_files: ./ui/supplemental_ui
#  bundle:
#    url: ./ui/build/ui-bundle.zip
#    snapshot: true

asciidoc:
  attributes:
    idprefix: ''
    stem: 'latexmath'
    page-pagination: ''
    experimental: ''

antora:
  extensions:
    - '@antora/lunr-extension'

output:
  destinations:
    - provider: fs
      path: ./public_html/
      clean: true
