[book]
title = "The Cairo Booklet"
description = "Cairo by Example (CBE) is a collection of runnable examples that illustrate various Cairo concepts and core libraries."
author = "The Cairo Community"

[output.html]
git-repository-url = "https://github.com/cairo-lang/cairo-by-example"
edit-url-template = "https://github.com/cairo-lang/cairo-by-example/edit/main/{path}"
additional-css = ["theme/css/last-changed.css", "theme/css/chat.css", "theme/css/hide-nav.css"]
additional-js = [
  "theme/wasm-cairo/pkg/wasm-cairo.js",
  "theme/wasm-cairo/pkg/wasm-cairo_bg.wasm",
  "theme/wasm-cairo/worker.cjs",
]
mathjax-support = true

[preprocessor.cairo]
after = ["links"]

[output.html.playground]
editable = true
# editor = "ace"
# line-numbers = true
runnable = true

[output.html.fold]
enable = true
level = 2

[rust]
edition = "2021"

[build]
extra-watch-dirs = ["po"]

[preprocessor.gettext]
after = ["links"]

[output.html.code.hidelines]
cairo = "# "

[output.markdown]
