cairo_resource_fee_weights:
  n_steps: 1.0
contract_storage_commitment_tree_height: 251
event_commitment_tree_height: 64
global_state_commitment_tree_height: 251
invoke_tx_max_n_steps: 1000000
min_gas_price: 100000000000
sequencer_address: '0x71acdec23a79f5c08ab668ee459c7c6fbb47de4ef14fcb94e9d04fa672ab3ec'
starknet_os_config:
  fee_token_address: '0x58c891da6c3b1ed062db42db3c6ca080724fabbe3d5073660d02aab8edc3e95'
tx_commitment_tree_height: 64
tx_version: 0
