name: Push workflow

on:
  push:
    branches:
      - master

jobs:
  release-version:
    name: Releasing a version
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'chore') || (github.ref_name == 'master' && !contains(github.event.head_commit.message, 'chore(release)')) }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install mdbook
        run: cargo install mdbook --locked --version 0.4.31
        shell: bash

      - name: Authenticate with GitHub
        run: |
          git config --global user.name "${{ secrets.USER_NAME }}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"

      - name: Build book (English)
        run: mdbook build -d book

      - name: Rename book to public_html
        run: mv book public_html

      - name: scp upload to production site
        run: sshpass -p ${{ secrets.PROD_PASS }} scp -o 'StrictHostKeyChecking no' -r public_html/ ${{ secrets.PROD_USER }}@${{ secrets.PROD_IP }}:~/
